jaeger:
  create: true
  name: jaeger
  agent:
    enabled: true
  collector:
    enabled: true
  query:
    enabled: true
  storage:
    type: memory
    memory:
      maxTraces: 100000
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - jaeger.aurora-dev.local
      