architecture: standalone

auth:
  enabled: true
  password: "aurora-redis-123"

master:
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

service:
  type: ClusterIP
  port: 6379
  