apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: aurora-dev
data:
  KAFKA_CFG_NODE_ID: "0"
  KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: aurora-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:3.7
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_NODE_ID
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CFG_NODE_ID
        - name: KAFKA_CFG_PROCESS_ROLES
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CFG_PROCESS_ROLES
        - name: KAFKA_CFG_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CFG_LISTENERS
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CFG_ADVERTISED_LISTENERS
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: aurora-dev
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
  type: ClusterIP
  