apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aurora-dev

resources:
- namespace.yaml
- service-account.yaml

commonLabels:
  app.kubernetes.io/part-of: aurora
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  version: v1alpha1
  environment: development
