prometheus:
  enabled: true
  prometheusSpec:
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelector: {}

grafana:
  enabled: true
  adminPassword: "aurora123"
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      aurora-overview:
        gnetId: 0
        datasource: Prometheus
        url: https://raw.githubusercontent.com/aurora-platform/dashboards/main/overview.json

alertmanager:
  enabled: false
  