# infrastructure/feast/feature_store.yaml
project: aurora_erp
registry: data/feature_store/registry.db
provider: local
online_store:
    type: sqlite
    path: data/feature_store/online_store.db
offline_store:
    type: file
entity_key_serialization_version: 3  # Updated to version 3 to fix deprecation..